# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: step_one
        run: |
          cat ~/.ssh/config
          git ls-remote -h -t ssh://git@github.com:sztwiorok/run.git
      - id: step_two
        run: |
          echo "Previous step output: ${{ steps.step_one.outputs.my_var }}"

