# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "MY_VAR=hello" >> $GITHUB_ENV
      - name: Use environment variable
        run: |
          echo "Environment variable: $MY_VAR"
          echo $GITHUB_ENV
          cat /home/runner/work/_temp/_runner_file_commands/set_env_e58d1b6d-4b11-4b3b-9cb3-c6889a9d48f2
  build2:
    runs-on: ubuntu-latest
    steps:
      - id: step_one
        run: |
          echo "::set-output name=my_var::$(echo hello)"
      - id: step_two
        run: |
          echo "Previous step output: ${{ steps.step_one.outputs.my_var }}"

