# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: s6
        run: |
           ssh -vvv git@github.com || true
           git config --global --get core.sshCommand || true
           cat ~/.ssh/known_hosts || true
           ssh -G git@github.com || true
           git config --global --list || true
           GIT_SSH_COMMAND="ssh -v" git ls-remote git@github.com:user/repo.git || true
           ssh -V || true
           

