# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: s1
        run: |
           cat /etc/ssh/ssh_known_hosts
      - id: s8
        run: |
          echo "Workflow name: $GITHUB_WORKFLOW"
          echo "Run number: $GITHUB_RUN_NUMBER"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Ref: $GITHUB_REF"
          
          # Use the workflow name in a filename
          echo "Build log" > ${GITHUB_WORKFLOW}-${GITHUB_RUN_NUMBER}.log
           

